### ISSUE TITLE
Undefined method rate_limit_retry_header and rate_limit_reset_header

### ISSUE THREAD

**Issue by djberg96** [lostisland/faraday-retry#34]
### Basic Version Info
faraday Version: 1.10.3
faraday-retry Version: 1.0.3
Ruby Version: 3.2.1

### Issue description

The README says that we can specify `rate_limit_retry_header` and `rate_limit_reset_header`. But, when I try to use these I get an undefined method error.

### Actual behavior

Backtrace: 
```
/Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/options.rb:33:in 'block in update': undefined method `rate_limit_reset_header=' for #<Faraday::Retry::Middleware::Options max=3, interval=2.0, max_interval=1.7976931348623157e+308, interval_randomness=0.0, backoff_factor=1.0, exceptions=[Errno::ETIMEDOUT, "Timeout::Error", Faraday::TimeoutError, Faraday::RetriableResponse], methods=[:delete, :get, :head, :options, :put], retry_if=#<Proc:0x0000000104c794a8 /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-retry-1.0.3/lib/faraday/retry/middleware.rb:31 (lambda)>, retry_block=#<Proc:0x0000000107fc61d0 /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-retry-1.0.3/lib/faraday/retry/middleware.rb:74>, retry_statuses=[401, 404, 500]> (NoMethodError)

        send("#{key}=", new_value) unless new_value.nil?
        ^^^^
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/options.rb:23:in `each'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/options.rb:23:in `update'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/options.rb:9:in `from'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-retry-1.0.3/lib/faraday/retry/middleware.rb:37:in `from'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-retry-1.0.3/lib/faraday/retry/middleware.rb:116:in `initialize'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/dependency_loader.rb:23:in `new'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/dependency_loader.rb:23:in `new'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:57:in `build'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:175:in `block in to_app'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:174:in `each'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:174:in `inject'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:174:in `to_app'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:167:in `app'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:154:in `build_response'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/connection.rb:516:in `run_request'
	from /Users/daniel.berger/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/faraday-1.10.3/lib/faraday/connection.rb:202:in `get'
	from faraday_retry_test.rb:23:in `<main>'
```

### Expected behavior

It should be honored (if present) or ignored (if not present) in the response header.

### Steps to reproduce
```ruby
# Simple example:

require 'faraday' # 1.x
require 'faraday/retry'

url = "http://www.someboguswebsite.com"

retry_options = {
  max: 3,
  interval: 2,
  retry_statuses: [401, 404, 500],
  rate_limit_retry_header: 'x-rate-limit-retry-after',
  rate_limit_reset_header: 'x-rate-limit-reset',
  retry_block: Proc.new{ |env|
    p env.status
  }
}

conn = Faraday.new(url: url) do |f|
  f.request :retry, retry_options
end

response = conn.get
p response.status
```

**Comment by olleolleolle** [comment]
👋 Hi! https://github.com/lostisland/faraday-retry/releases You may see that faraday-retry 1.x supports the Faraday 1.x release series, and that Faraday 2.x is supported by the newer releases of https://github.com/lostisland/faraday-retry/

**Comment by olleolleolle** [comment]
The feature was introduced in 2.0.1 or 2.1 if I read the logs correctly

**Comment by djberg96** [comment]
@olleolleolle Roger that, closing, thanks.
